services:

  vaultwarden:

    image: vaultwarden/server:latest

    container_name: vaultwarden

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - /opt/quesadalab/data/vaultwarden:/data

    networks:
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      - "traefik.http.routers.vault.rule=Host(`vault.lab`)"
      - "traefik.http.routers.vault.entrypoints=websecure"
      - "traefik.http.routers.vault.tls=true"
      - "traefik.http.routers.vault.middlewares=lan-only@file,security-headers@file"

      - "traefik.http.services.vault.loadbalancer.server.port=80"

networks:

  proxy:
    external: true
