services:
  uptime-kuma:
    image: louislam/uptime-kuma:1

    container_name: uptime-kuma

    restart: unless-stopped

    volumes:
      - /opt/quesadalab/data/uptime-kuma:/app/data

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.kuma.rule=Host(`kuma.lab`)"
      - "traefik.http.routers.kuma.entrypoints=web"

      - "traefik.http.routers.kuma.middlewares=lan-only@file,security-headers@file"

      - "traefik.http.services.kuma.loadbalancer.server.port=3001"

networks:
  proxy:
    external: true
